proxmox:
  hosts:
    proxmox2:
      ansible_host: "{{ ip_address.proxmox2 }}"
      ansible_user: "{{ proxmox2.user }}"
      ansible_connection: "ssh"
      ansible_ssh_private_key_file: "{{ proxmox2.sshkeypath }}"
