---
# tasks to be completed before running roles
- name: Pre-run
  hosts: localhost
  connection: local
  become: true
    #  gather_facts: true
  pre_tasks:
    - name: Pre-run | update package cache (debian, etc.)
      ansible.builtin.apt:
        update_cache: true # equivalent of "apt-get update"
        cache_valid_time: 3600 # only run if the last one is more than 3600 seconds ago
      changed_when: false # never report 'changed' status
      when: ansible_facts['os_family'] == 'Debian'

# run roles
- name: Roles common to all
  hosts: localhost
  connection: local
  become: true
    #  gather_facts: true
  tasks:
    - name: Include role | common
      ansible.builtin.include_role:
        name: common

# end of run cleanup and reporting
