---
- hosts: localhost
  connection: local
  become: true

  tasks:
# ---- ---- ---- apt package manager tasks ---- ---- ----
  - name: copy apt source list
    copy:
      src: files/sources.list
      dest: /etc/apt/sources.list
      owner: root
      group: root
      mode: 0644 #-rw-r--r--

  - name: apt-get update, apt-get dist-upgrade
    ansible.builtin.apt:
      update_cache: true
      upgrade: dist

  - name: install packages
    package:
      name:
        - vim
        - tree #command for directory tree listing
        - htop
        - dconf-cli #configuration system from GNOME desktop environment. required for wallpaper task below.
        - python3-psutil #needed IOT set the wallpaper position below
        - flatpak
        - gnome-software-plugin-flatpak
        - syncthing #decentralized file synchronization
        - steam-devices #Device support for Steam-related hardware
      state: present

  - name: install CFD workstation packages
    package:
      name:
        - paraview
      state: present

  - name: remove packages
    package:
      name:
        - firefox-esr
        - libreoffice
        - libreoffice-common
        - libreoffice-core
        - libreoffice-gnome
        - libreoffice-gtk3
        - libreoffice-help-common
        - libreoffice-help-en-us
        - libreoffice-help-en-gb
        - libreoffice-style-colibre
        - libreoffice-style-elementary
        - nano
      state: absent
      purge: yes

  - name: remove dependencies that are no longer required
    package:
      autoremove: yes

# ---- ---- ---- Set Wallpaper ---- ---- ----
  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: jwhite
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

  - name: set wallpaper position
    become_user: jwhite
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

# ---- ---- ---- Add ansible cron job ---- ---- ----
  - name: add ansible user
    user:
      name: ansible_user
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansible_user
      dest: /etc/sudoers.d/ansible_user
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansible_user
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/JoshuaJWhite/ansible.git

  - name: add the flathub flatpak repository remote to the user installation
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

# ---- ---- ---- Flatpack ---- ---- ----
  - name: install multiple package from flathub
    community.general.flatpak:
      name:
        - org.mozilla.firefox
        - org.libreoffice.LibreOffice
        - com.valvesoftware.Steam
        - org.gimp.GIMP
        - org.freecadweb.FreeCAD
        - io.github.jonmagon.kdiskmark
        - tv.plex.PlexDesktop
        - com.moonlight_stream.Moonlight
      state: present

# ---- ---- ---- Bashrc ---- ---- ----
  - name: copy bashrc file
    copy:
      src: files/bashrc
      dest: /home/jwhite/.bashrc
      owner: jwhite
      group: jwhite
      mode: 0644 #-rw-r--r--

# ---- ---- ---- Nvidia Hybrid Laptop ---- ---- ----
  - name: install nvidia driver
    package:
      name:
        - nvidia-driver
      state: present

  - name: copy nvidia udev rule for hybrid operation
    copy:
      src: files/80-nvidia-pm.rules
      dest: /etc/udev/rules.d/80-nvidia-pm.rules
      owner: root
      group: root

  - name: copy nvidia module parameter for hybrid operation
    copy:
      src: files/nvidia-pm.conf
      dest: /etc/modprobe.d/nvidia-pm.conf
      owner: root
      group: root

  - name: systemd nvidia persistence service
    ansible.builtin.systemd:
      name: nvidia-persistenced.service
      enabled: true
