#            _
#  _ __ ___ | | ___ _   _ __  _ __ _____  ___ __ ___   _____  __
# | '__/ _ \| |/ _ (_) | '_ \| '__/ _ \ \/ / '_ ` _ \ / _ \ \/ /
# | | | (_) | |  __/_  | |_) | | | (_) >  <| | | | | | (_) >  <
# |_|  \___/|_|\___(_) | .__/|_|  \___/_/\_\_| |_| |_|\___/_/\_\
#                      |_|
# main.yml for role for proxmox server

- name: Role proxmox | import system_sourceslist.yml
  ansible.builtin.import_tasks:
    file: system_sourceslist.yml

- name: Role proxmox | import system_ssh.yml
  ansible.builtin.import_tasks:
    file: system_ssh.yml

- name: Role proxmox | import packages_cli.yml
  ansible.builtin.import_tasks:
    file: packages_cli.yml

- name: Role proxmox | import system_bashrc.yml
  ansible.builtin.import_tasks:
    file: system_bashrc.yml

- name: Role proxmox | import system_vimrc.yml
  ansible.builtin.import_tasks:
    file: system_vimrc.yml

- name: Role proxmox | import system_iommu.yml
  ansible.builtin.import_tasks:
    file: system_iommu.yml

- name: Role proxmox | import system_passthrough.yml
  ansible.builtin.import_tasks:
    file: system_passthrough.yml

- name: Role proxmox | import system_alerts.yml
  ansible.builtin.import_tasks:
    file: system_alerts.yml

# this task hangs the playbook... not sure why yet
# ref: https://johnscs.com/remove-proxmox51-subscription-notice/
# - name: Role proxmox | import system_pvenag.yml
#  ansible.builtin.import_tasks:
#    file: system_pvenag.yml
