- name: System | ssh | disable ssh password auth
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication yes'
    line: 'PasswordAuthentication no'
  register: sshd_config

- name: System | ssh | restart ssh daemon
  ansible.builtin.service:
    name: "sshd"
    state: "restarted"
  when: sshd_config.changed
