- name: System | source list | remove Proxmox VE Enterprise Repo
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    regexp: '^deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'
    line: '#deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'
    state: "present"
- name: System | source list | add Proxmox VE Enterprise Repo
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    line: 'deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription'
    state: "present"

- name: System | source list | remove Ceph Reff Enterprise Repo
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/ceph.list
    regexp: '^deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise'
    line: '#deb https://enterprise.proxmox.com/debian/ceph-quincy bookworm enterprise'
    state: "present"
- name: System | source list | add  Ceph Reff No-Subscription Repo
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/ceph.list
    line: 'deb http://download.proxmox.com/debian/ceph-reef bookworm no-subscription'
    state: "present"
