- name: System | iommu | kernel command line
  ansible.builtin.lineinfile:
    path: /etc/kernel/cmdline
    regexp: '^root=ZFS=rpool/ROOT/pve-1 boot=zfs.*'
    line: 'root=ZFS=rpool/ROOT/pve-1 boot=zfs quiet intel_iommu=on iommu=pt'
    state: "present"
    backup: true
  register: kcmdline_config

- name: System | iommu | update all config files in loader
  ansible.builtin.shell:
    cmd: proxmox-boot-tool refresh
  when: kcmdline_config.changed

- name: System | iommu | kernel modules
  ansible.builtin.blockinfile:
    path: /etc/modules
    create: true
    owner: root
    group: root
    mode: '0644' # -rw-r--r--
    state: "present"
    backup: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK | proxmox"
    block: |
      vfio
      vfio_iommu_type1
      vfio_pci
  register: kmodules_config

- name: System | iommu | update initramfs
  ansible.builtin.shell:
    cmd: update-initramfs -u -k all
  when: kmodules_config.changed
