#            _                             _        _        _   _
#  _ __ ___ | | ___ _  __      _____  _ __| | _____| |_ __ _| |_(_) ___  _ __
# | '__/ _ \| |/ _ (_) \ \ /\ / / _ \| '__| |/ / __| __/ _` | __| |/ _ \| '_ \
# | | | (_) | |  __/_   \ V  V / (_) | |  |   <\__ \ || (_| | |_| | (_) | | | |
# |_|  \___/|_|\___(_)   \_/\_/ \___/|_|  |_|\_\___/\__\__,_|\__|_|\___/|_| |_|
# main.yml in roles for workstation machines

- name: Role workstation | import package_flatpak.yml
  ansible.builtin.import_tasks:
    file: packages_flatpak.yml

- name: Role workstation | import package_sunshine.yml
  ansible.builtin.import_tasks:
    file: packages_sunshine.yml

- name: Role workstation | import system_network.yml
  ansible.builtin.import_tasks:
    file: system_network.yml

- name: Role workstation | import system_autologin.yml
  ansible.builtin.import_tasks:
    file: system_autologin.yml

- name: Role workstation | import system_autolock.yml
  ansible.builtin.import_tasks:
    file: system_autolock.yml

- name: Role workstation | import system_mount.yml
  ansible.builtin.import_tasks:
    file: system_mount.yml

- name: Role workstation | import packages_vscode.yml
  ansible.builtin.import_tasks:
    file: packages_vscode.yml
