- name: Packages | install | sunshine | install .deb
  ansible.builtin.apt:
    deb: https://github.com/LizardByte/Sunshine/releases/latest/download/sunshine-debian-bookworm-amd64.deb
    state: present
  when:
    - ansible_facts['pkg_mgr'] == 'apt'
    - ansible_facts['distribution'] == 'Debian'
    - ansible_facts['distribution_release'] == 'bookworm'

- name: Packages | install | sunshine | check if installed
  ansible.builtin.command:
    cmd: dpkg-query -W sunshine
  register: check_sunshine_deb_installed # rc=0 <- installed, rc=1 <- not installed
  failed_when: check_sunshine_deb_installed.rc > 1 # rc>1 <- failed
  changed_when: false
  when: ansible_facts['pkg_mgr'] == 'apt'

- name: Packages| install | sunshine | create ~/.config/autostart/
  ansible.builtin.file:
    path: /home/{{ user.standard }}/.config/autostart/
    state: "directory"
    owner: "{{ user.standard }}"
    group: "{{ user.standard }}"
    mode: '0755' # drwxr-xr-x
  changed_when: false # otherwise always changed

# - name: Packages | install | sunshine | copy included .desktop to autostart
#  ansible.builtin.copy:
#    src: /usr/share/applications/sunshine.desktop
#    dest: /home/{{ user.standard }}/.config/autostart/sunshine.desktop
#    owner: "{{ user.standard }}"
#    group: "{{ user.standard }}"
#    mode: '0644' # -rw-r--r--
#    force: false
#  when: check_sunshine_deb_installed.rc == 0 # rc=0 <- installed

# - name: Packages | install | sunshine | turn off terminal for autostart
#  ansible.builtin.lineinfile:
#    path: /home/{{ user.standard }}/.config/autostart/sunshine.desktop
#    regexp: '^Terminal=.*'
#    line: 'Terminal=false'
#    create: false
#  when: check_sunshine_deb_installed.rc == 0 # rc=0 <- installed

- name: Packages | install | sunshine | no cursor workaround
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: '^MUTTER_DEBUG_DISABLE_HW_CURSORS=.*'
    line: 'MUTTER_DEBUG_DISABLE_HW_CURSORS=1'
    create: true
    owner: "root"
    group: "root"
    mode: '0644' # -rw-r--r--
  when: check_sunshine_deb_installed.rc == 0 # rc=0 <- installed

- name: Packages | install | sunshine | create .config/systemd/user directory
  ansible.builtin.file:
    path: /home/{{ user.standard }}/.config/systemd/user/
    state: "directory"
    owner: "{{ user.standard }}"
    group: "{{ user.standard }}"
    mode: '0755' # drwxr-xr-x
  when: check_sunshine_deb_installed.rc == 0 # rc=0 <- installed

- name: Packages | install | sunshine | create systemd service
  ansible.builtin.blockinfile:
    path: /home/{{ user.standard }}/.config/systemd/user/sunshine.service
    create: true
    owner: "{{ user.standard }}"
    group: "{{ user.standard }}"
    mode: '0744' # -rwxr--r--
    marker: "# {mark} ANSIBLE MANAGED BLOCK | role=workstation"
    block: |
      [Unit]
      Description=Sunshine self-hosted game stream host for Moonlight.
      StartLimitIntervalSec=500
      StartLimitBurst=5

      [Service]
      ExecStart=/usr/bin/sunshine
      Restart=on-failure
      RestartSec=5s

      [Install]
      WantedBy=graphical-session.target
  when: check_sunshine_deb_installed.rc == 0 # rc=0 <- installed

- name: Packages | install | sunshine | systemd service start enable
  ansible.builtin.systemd_service:
    name: sunshine.service
    state: "started"
    enabled: true
    scope: "user"
  become_user: "{{ user.standard }}"
  when: check_sunshine_deb_installed.rc == 0 # rc=0 <- installed
