- name: System | static network eth0
  community.general.nmcli:
    conn_name: eth0
    ifname: "{{ workstation0.interface_lan }}"
    type: "ethernet"
    ip4: "{{ ip_address.workstation0_lan }}/24"
    gw4: "{{ ip_address.gateway }}"
    dns4: "{{ ip_address.gateway }}"
    mtu: 1500
    route_metric4: 100
    autoconnect: true
    state: "present"

- name: System | static network eth9000
  community.general.nmcli:
    conn_name: eth9000
    ifname: "{{ workstation0.interface_local }}"
    type: "ethernet"
    ip4: "{{ ip_address.workstation0_local }}/24"
    mtu: 9000
    autoconnect: true
    state: "present"

- name: System | remove default Wired connection 1
  community.general.nmcli:
    conn_name: "Wired connection 1"
    state: "absent"

- name: System | static network eth10gbe
  community.general.nmcli:
    conn_name: eth10gbe
    ifname: "{{ workstation0.interface_10gbe }}"
    type: "ethernet"
    ip4: "{{ ip_address.workstation0_10gbe }}/24"
    mtu: 9000
    autoconnect: true
    state: "present"
