- name: System | auto-login on
  ansible.builtin.lineinfile:
    path: /etc/gdm3/daemon.conf
    regexp: 'AutomaticLoginEnable =.*'
    line: 'AutomaticLoginEnable = true'
    create: false

- name: System | auto-login user set
  ansible.builtin.lineinfile:
    path: /etc/gdm3/daemon.conf
    regexp: 'AutomaticLogin =.*'
    line: "AutomaticLogin = {{ user.standard }}"
    create: false
