- name: System | auto-login on
  ansible.builtin.lineinfile:
    path: /etc/gdm3/daemon.conf
    regexp: '^#  AutomaticLoginEnable = true'
    line: 'AutomaticLoginEnable=true'
    create: false

- name: System | auto-login user set
  ansible.builtin.lineinfile:
    path: /etc/gdm3/daemon.conf
    regexp: '^#  AutomaticLogin = user1'
    line: "AutomaticLogin={{ user.standard }}"
    create: false
