- name: Packages | install | cli tools
  ansible.builtin.apt:
    name:
      - curl
      - figlet # for making text banners of ASCII characters
      - fio # flexible I/O tester
      - git
      - gnuplot
      - htop
      - intel-gpu-tools # tools for debugging the Intel graphics driver
      - iotop # simple top-like I/O monitor
      - iperf3 # Internet Protocol bandwidth measuring tool
      - lf # range inspired file manager
      - neofetch # Shows Linux System Information with Distribution Logo
      - stress # tool to impose load on and stress test a computer system
      - tree
      - vim
      - vifm # flexible vi-like file manager using ncurses
      - xz-utils
    state: present
  when: ansible_facts['pkg_mgr'] == 'apt'
