- name: Packages | install | ansible tools
  ansible.builtin.apt:
    name:
      - ansible
      - ansible-lint
      - git
      - cron
      - xz-utils
    state: present
  when: ansible_facts['pkg_mgr'] == 'apt'
