- name: Packages | install | cli tools
  ansible.builtin.apt:
    name:
      - curl
      - figlet # for making text banners of ASCII characters
      - git
      - htop
      - iotop # simple top-like I/O monitor
      - iperf3 # Internet Protocol bandwidth measuring tool
      - lf # range inspired file manager
      - neofetch # Shows Linux System Information with Distribution Logo
      - tree
      - vim
      - vifm # flexible vi-like file manager using ncurses
    state: present
  when: ansible_facts['pkg_mgr'] == 'apt'
