- name: System | ansible | add ansible user
  ansible.builtin.user:
    name: "{{ user.ansible }}"
    system: true
    state: present
    create_home: false

- name: System | ansible | set sudo permissions for ansible user
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ user.ansible }}"
    regexp: "^{{ user.ansible }} ALL=(ALL) NOPASSWD: ALL"
    line: "{{ user.ansible }} ALL=(ALL) NOPASSWD: ALL"
    create: true
    owner: "root"
    group: "root"
    mode: '0440' # -r--r-----

- name: System | ansible | create ansible log file
  ansible.builtin.file:
    path: /var/log/ansible-pull.log
    owner: "{{ user.ansible }}"
    group: "{{ user.ansible }}"
    mode: "0664" # -rw-rw-r--
    state: touch
  changed_when: false

- name: System | ansible | cron job for ansible-pull on changes
  ansible.builtin.cron:
    name: ansible-pull
    user: "{{ user.ansible }}"
    minute: "*/10"
    state: present
    job: >
      sudo /usr/bin/ansible-pull
      --only-if-changed
      --vault-password-file {{ path.key }}
      -U https://github.com/JoshuaJWhite/ansible.git
      2>&1 | tee /var/log/ansible-pull.log

- name: System | ansible | cron job for ansible-pull at midnight
  ansible.builtin.cron:
    name: ansible-pull
    user: "{{ user.ansible }}"
    minute: "0"
    hour: "0"
    state: present
    job: >
      sudo /usr/bin/ansible-pull
      --vault-password-file {{ path.key }}
      -U https://github.com/JoshuaJWhite/ansible.git
      2>&1 | tee /var/log/ansible-pull.log

- name: System | ansible | cron job for ansible-pull at boot
  ansible.builtin.cron:
    name: ansible-pull
    user: "{{ user.ansible }}"
    special_time: reboot
    state: present
    job: >
      sudo /usr/bin/ansible-pull
      --vault-password-file {{ path.key }}
      -U https://github.com/JoshuaJWhite/ansible.git
      2>&1 | tee /var/log/ansible-pull.log
