- name: System | bashrc
  ansible.builtin.blockinfile:
    path: /home/{{ user.standard }}/.bashrc
    create: true
    owner: "{{ user.standard }}"
    group: "{{ user.standard }}"
    mode: '0644'
    insertafter: "EOF"
    block: |
      # user aliases
      alias ll='ls -laFh'
      alias l='ls -CF'
      alias reboot="sudo systemctl reboot"
      alias poweroff="sudo systemctl poweroff"
      alias hibernate="sudo systemctl hibernate"
    marker: "# {mark} ANSIBLE MANAGED BLOCK | common"
