#            _               _ _            _
#  _ __ ___ | | ___ _    ___| (_) ___ _ __ | |_
# | '__/ _ \| |/ _ (_)  / __| | |/ _ \ '_ \| __|
# | | | (_) | |  __/_  | (__| | |  __/ | | | |_
# |_|  \___/|_|\___(_)  \___|_|_|\___|_| |_|\__|
# main.yml for roles for client machines

- name: Role client | import packages_flatpak.yml
  ansible.builtin.import_tasks:
    file: packages_flatpak.yml
